package Telas;

import BancoDeDados.Insert_Banco;
import BancoDeDados.Select_Banco;
import BancoDeDados.Update_Banco;
import Classes.Classificacao_Etaria;
import Classes.Estudio;
import Classes.Historico_Series;
import Classes.Historico_Usuario;
import Classes.Links;
import Classes.Nacionalidade;
import Classes.Series;
import Classes.Sessao;
import Classes.Status;
import Controle.Convert;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author bissm
 */
public class tela_Serie extends javax.swing.JFrame {

    /**
     * Creates new form tela_Serie
     */
    public tela_Serie() {
        initComponents();

    }

    public tela_Serie(List<Series> a) {
        initComponents();
        iniciar(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_img = new javax.swing.JButton();
        tb_link = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        bt_MaisTemp = new javax.swing.JButton();
        bt_MenenosTemp = new javax.swing.JButton();
        bt_MaisEp = new javax.swing.JButton();
        bt_MenosEp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lb_temporada = new javax.swing.JLabel();
        lb_ep = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tb_Nome = new javax.swing.JTextField();
        tb_Duracao = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_Favorito = new javax.swing.JCheckBox();
        cb_Dublado = new javax.swing.JCheckBox();
        cb_Legendado = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cb_Classificacao = new javax.swing.JTextField();
        cb_Estudio = new javax.swing.JTextField();
        cb_Nacionalidade = new javax.swing.JTextField();
        cb_Status = new javax.swing.JTextField();
        cb_nota = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_img.setText("img");
        bt_img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_imgActionPerformed(evt);
            }
        });

        tb_link.setText("https://");
        tb_link.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_linkActionPerformed(evt);
            }
        });

        jButton6.setText("Atualizar Historico");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        bt_MaisTemp.setText("+");
        bt_MaisTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_MaisTempActionPerformed(evt);
            }
        });

        bt_MenenosTemp.setText("-");
        bt_MenenosTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_MenenosTempActionPerformed(evt);
            }
        });

        bt_MaisEp.setText("+");
        bt_MaisEp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_MaisEpActionPerformed(evt);
            }
        });

        bt_MenosEp.setText("-");
        bt_MenosEp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_MenosEpActionPerformed(evt);
            }
        });

        jLabel2.setText("Temporada Atual");

        jLabel3.setText("Ep. Atual");

        jLabel4.setText("Link's");

        jLabel5.setText("00/");

        lb_temporada.setText("00");

        lb_ep.setText("00");

        jLabel8.setText("00/");

        try {
            tb_Duracao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tb_Duracao.setText("00:00");
        tb_Duracao.setToolTipText("");
        tb_Duracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_DuracaoActionPerformed(evt);
            }
        });

        jLabel7.setText("Nacionalidade");

        jLabel6.setText("Estudio");

        jLabel9.setText("Classificação");

        cb_Favorito.setText("Favorito");

        cb_Dublado.setText("Dublado");
        cb_Dublado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_DubladoActionPerformed(evt);
            }
        });

        cb_Legendado.setText("Legendado");

        jLabel1.setText("Nome");

        jLabel10.setText("Duração");

        jLabel11.setText("Nota");

        jLabel12.setText("Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bt_img, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_Dublado)
                            .addComponent(cb_Legendado)
                            .addComponent(cb_Favorito))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cb_Status))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cb_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_Nacionalidade)
                                    .addComponent(cb_Estudio, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(tb_link, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tb_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tb_Duracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(71, 71, 71)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cb_Classificacao))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(lb_temporada)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(bt_MenenosTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bt_MaisTemp))
                                            .addComponent(jLabel5))
                                        .addGap(86, 86, 86)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(17, 17, 17)
                                                        .addComponent(lb_ep))
                                                    .addComponent(jLabel8))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bt_MenosEp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bt_MaisEp))
                                            .addComponent(jLabel3))))
                                .addGap(0, 51, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jButton6)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tb_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tb_Duracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(cb_Classificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11)
                            .addComponent(cb_Estudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(cb_Nacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cb_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_MaisEp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bt_MenosEp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)
                                        .addComponent(lb_ep))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_MaisTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bt_MenenosTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addComponent(lb_temporada)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tb_link, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(bt_img, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_Favorito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_Dublado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_Legendado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_imgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_imgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_imgActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int nTemp = Integer.parseInt(lb_temporada.getText());
        int nEp = Integer.parseInt(lb_ep.getText());
        Select_Banco in = new Select_Banco();
        List<Series> lista = new ArrayList();
        lista = in.Select_SeriesEdit1(tb_Nome.getText());
        int idS = lista.get(0).id;
        int idU = Sessao.getId();
        Historico_Usuario HU = in.Select_Historico_User(idU, idS);
        if (HU.id==0) {
            Insert_Banco i = new Insert_Banco();
            i.Insert_Historico_Usuario(nTemp, nEp, Sessao.getId());
            Historico_Series hS = in.Select_HistoricoUser(idS);
            int idH = hS.getFK_Historico();
            salvarLink(idH, idS);
        } else {
            Update_Banco up = new Update_Banco();
            up.Update_Historico_Usuario(nTemp, nEp, Sessao.getHU());
            salvarLink(0, idS);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void bt_MaisTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_MaisTempActionPerformed
        int x = Integer.parseInt(lb_temporada.getText());
        x += 01;
        lb_temporada.setText(Integer.toString(x));
    }//GEN-LAST:event_bt_MaisTempActionPerformed

    private void bt_MenenosTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_MenenosTempActionPerformed
        int x = Integer.parseInt(lb_temporada.getText());
        x--;
        lb_temporada.setText(Integer.toString(x));
    }//GEN-LAST:event_bt_MenenosTempActionPerformed

    private void bt_MenosEpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_MenosEpActionPerformed
        int x = Integer.parseInt(lb_ep.getText());
        x--;
        lb_ep.setText(Integer.toString(x));
    }//GEN-LAST:event_bt_MenosEpActionPerformed

    private void bt_MaisEpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_MaisEpActionPerformed
        int x = Integer.parseInt(lb_ep.getText());
        x++;
        lb_ep.setText(Integer.toString(x));
    }//GEN-LAST:event_bt_MaisEpActionPerformed

    private void tb_DuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_DuracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_DuracaoActionPerformed

    private void cb_DubladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_DubladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_DubladoActionPerformed

    private void tb_linkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_linkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_linkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_Serie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_Serie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_Serie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_Serie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_Serie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_MaisEp;
    private javax.swing.JButton bt_MaisTemp;
    private javax.swing.JButton bt_MenenosTemp;
    private javax.swing.JButton bt_MenosEp;
    private javax.swing.JButton bt_img;
    private javax.swing.JTextField cb_Classificacao;
    private javax.swing.JCheckBox cb_Dublado;
    private javax.swing.JTextField cb_Estudio;
    private javax.swing.JCheckBox cb_Favorito;
    private javax.swing.JCheckBox cb_Legendado;
    private javax.swing.JTextField cb_Nacionalidade;
    private javax.swing.JTextField cb_Status;
    private javax.swing.JTextField cb_nota;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lb_ep;
    private javax.swing.JLabel lb_temporada;
    private javax.swing.JFormattedTextField tb_Duracao;
    private javax.swing.JTextField tb_Nome;
    private javax.swing.JTextField tb_link;
    // End of variables declaration//GEN-END:variables

    private void iniciar(List<Series> a) {
        tb_Nome.setText(a.get(0).nome);
        tb_Duracao.setText(a.get(0).Duracao);
        cb_Dublado.setSelected(a.get(0).Dublado);
        cb_Favorito.setSelected(a.get(0).Favorito);
        cb_Legendado.setSelected(a.get(0).Legendado);
        cb_nota.setText(Integer.toString(a.get(0).Nota));
        ImageIcon i = Convert.getImagem(a.get(0).Imagem);
            Select_Banco in = new Select_Banco();   
            List<Series> lista = new ArrayList();
            lista = in.Select_SeriesEdit1(tb_Nome.getText());
            int idS = lista.get(0).id;
            int idU = Sessao.getId();
                    
            boolean v = in.Select_Link_Series(idS);
            if (v) {
                int idLink = in.Select_Link_Series2(idS);
                String lin = in.Select_Link2(idLink);
                tb_link.setText(lin);
            }
           
            Historico_Usuario HU = in.Select_Historico_User1(idU, idS);                           
            String ep = Integer.toString(HU.getEpisodio_Atual());
            String temp = Integer.toString(HU.getTemporada_Atual());
                lb_ep.setText(ep);
                lb_temporada.setText(temp);
                
                    
           //Get itens lb_ep e lb_Temp

        if (i != null) {
            ImageIcon x = Convert.getImagem(a.get(0).Imagem);
            x.setImage(x.getImage().getScaledInstance(bt_img.getWidth(), bt_img.getHeight(), 1));
            bt_img.setText("");
            bt_img.setIcon(x);
        }
        List<Status> listaStatus = new ArrayList();
        List<Classificacao_Etaria> listaClass = new ArrayList();
        List<Estudio> listaEstudio = new ArrayList();
        List<Nacionalidade> listaNac = new ArrayList();
        int Status = a.get(0).FK_Status;
        int Classif = a.get(0).FK_Classificacao;
        int Estudio = a.get(0).FK_Estudio;
        int Nacio = a.get(0).FK_Nacionalidade;
        Select_Banco sec = new Select_Banco();
        listaStatus = sec.Select_Status1(Status);
        cb_Status.setText(listaStatus.get(0).Status_Producao);
        listaClass = sec.Select_Classificacao_Etaria1(Classif);
        cb_Classificacao.setText(listaClass.get(0).Classificacao);
        listaEstudio = sec.Select_Estudio1(Estudio);
        cb_Estudio.setText(listaEstudio.get(0).Nome_Estudio);
        listaNac = sec.Select_Nacionalidade1(Nacio);
        cb_Nacionalidade.setText(listaNac.get(0).Pais);

    }

    private void salvarLink(int idH, int idS) {
        Select_Banco in =new Select_Banco();
        boolean x = in.Select_Link_Series(idS);

        if(!x){
            Insert_Banco i = new Insert_Banco();
            i.Insert_Historico_Series(idH, idS);
            String link = tb_link.getText();
            i.Insert_Links(link);
            Links lin = in.Select_Link(link);
            i.Insert_Series_Link(idS, lin.getId());
        }else{
            Update_Banco up = new Update_Banco();
            String link = tb_link.getText();
            int idLink = in.Select_Link_Series2(idS);
            up.Update_Link(idLink, link);
        }
    }
}